services:
  - type: web
    name: moviehub-api
    env: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: MONGO_URI
        sync: false
      - key: OMDB_API_KEY
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_ID
        sync: false
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: PORT
        value: 10000
      - key: PYTHON_VERSION
        value: 3.10.0

  - type: worker
    name: moviehub-bot
    env: python
    buildCommand: pip install -r admin_bot/requirements.txt
    startCommand: python admin_bot/bot.py
    envVars:
      - key: MONGO_URI
        sync: false
      - key: OMDB_API_KEY
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_ID
        sync: false
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: PYTHON_VERSION
        value: 3.10.0
